import type { AlgorithmCode } from './types';

export const algorithmCodes: Record<string, AlgorithmCode> = {
  bubble: {
    pseudo: [
      'procedure bubbleSort(arr[], n)',
      '  for i = 0 to n-2',
      '    for j = 0 to n-i-2',
      '      if arr[j] > arr[j+1]',
      '        swap(arr[j], arr[j+1])',
      '      end if',
      '    end for',
      '  end for',
      'end procedure',
    ],
    javascript: [
      'function bubbleSort(arr) {',
      '  const n = arr.length;',
      '  for (let i = 0; i < n - 1; i++) {',
      '    for (let j = 0; j < n - i - 1; j++) {',
      '      if (arr[j] > arr[j + 1]) {',
      '        [arr[j], arr[j+1]] = [arr[j+1], arr[j]];',
      '      }',
      '    }',
      '  }',
      '}',
    ],
    python: [
      'def bubble_sort(arr):',
      '    n = len(arr)',
      '    for i in range(n - 1):',
      '        for j in range(n - i - 1):',
      '            if arr[j] > arr[j + 1]:',
      '                arr[j], arr[j+1] = arr[j+1], arr[j]',
      '',
      '',
      '',
      '',
    ],
    cpp: [
      'void bubbleSort(int arr[], int n) {',
      '  ',
      '  for (int i = 0; i < n - 1; i++) {',
      '    for (int j = 0; j < n - i - 1; j++) {',
      '      if (arr[j] > arr[j + 1]) {',
      '        swap(arr[j], arr[j + 1]);',
      '      }',
      '    }',
      '  }',
      '}',
    ],
    java: [
      'void bubbleSort(int[] arr) {',
      '  int n = arr.length;',
      '  for (int i = 0; i < n - 1; i++) {',
      '    for (int j = 0; j < n - i - 1; j++) {',
      '      if (arr[j] > arr[j + 1]) {',
      '        int temp = arr[j];',
      '        arr[j] = arr[j + 1];',
      '        arr[j + 1] = temp;',
      '      }',
      '    }',
      '  }',
      '}',
    ],
  },

  selection: {
    pseudo: [
      'procedure selectionSort(arr[], n)',
      '  for i = 0 to n-2',
      '    minIndex = i',
      '    for j = i+1 to n-1',
      '      if arr[j] < arr[minIndex]',
      '        minIndex = j',
      '      end if',
      '    end for',
      '    swap(arr[i], arr[minIndex])',
      '  end for',
      'end procedure',
    ],
    javascript: [
      'function selectionSort(arr) {',
      '  const n = arr.length;',
      '  for (let i = 0; i < n - 1; i++) {',
      '    let minIdx = i;',
      '    for (let j = i + 1; j < n; j++) {',
      '      if (arr[j] < arr[minIdx]) {',
      '        minIdx = j;',
      '      }',
      '    }',
      '    [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];',
      '  }',
      '}',
    ],
    python: [
      'def selection_sort(arr):',
      '    n = len(arr)',
      '    for i in range(n - 1):',
      '        min_idx = i',
      '        for j in range(i + 1, n):',
      '            if arr[j] < arr[min_idx]:',
      '                min_idx = j',
      '        ',
      '        arr[i], arr[min_idx] = arr[min_idx], arr[i]',
      '',
      '',
      '',
    ],
    cpp: [
      'void selectionSort(int arr[], int n) {',
      '  ',
      '  for (int i = 0; i < n - 1; i++) {',
      '    int minIdx = i;',
      '    for (int j = i + 1; j < n; j++) {',
      '      if (arr[j] < arr[minIdx]) {',
      '        minIdx = j;',
      '      }',
      '    }',
      '    swap(arr[i], arr[minIdx]);',
      '  }',
      '}',
    ],
    java: [
      'void selectionSort(int[] arr) {',
      '  int n = arr.length;',
      '  for (int i = 0; i < n - 1; i++) {',
      '    int minIdx = i;',
      '    for (int j = i + 1; j < n; j++) {',
      '      if (arr[j] < arr[minIdx]) {',
      '        minIdx = j;',
      '      }',
      '    }',
      '    int temp = arr[i];',
      '    arr[i] = arr[minIdx];',
      '    arr[minIdx] = temp;',
      '  }',
      '}',
    ],
  },

  insertion: {
    pseudo: [
      'procedure insertionSort(arr[], n)',
      '  for i = 1 to n-1',
      '    key = arr[i]',
      '    j = i - 1',
      '    while j >= 0 and arr[j] > key',
      '      arr[j+1] = arr[j]',
      '      j = j - 1',
      '    end while',
      '    arr[j+1] = key',
      '  end for',
      'end procedure',
    ],
    javascript: [
      'function insertionSort(arr) {',
      '  const n = arr.length;',
      '  for (let i = 1; i < n; i++) {',
      '    let key = arr[i];',
      '    let j = i - 1;',
      '    while (j >= 0 && arr[j] > key) {',
      '      arr[j + 1] = arr[j];',
      '      j--;',
      '    }',
      '    arr[j + 1] = key;',
      '  }',
      '}',
    ],
    python: [
      'def insertion_sort(arr):',
      '    n = len(arr)',
      '    for i in range(1, n):',
      '        key = arr[i]',
      '        j = i - 1',
      '        while j >= 0 and arr[j] > key:',
      '            arr[j + 1] = arr[j]',
      '            j -= 1',
      '        arr[j + 1] = key',
      '',
      '',
      '',
    ],
    cpp: [
      'void insertionSort(int arr[], int n) {',
      '  ',
      '  for (int i = 1; i < n; i++) {',
      '    int key = arr[i];',
      '    int j = i - 1;',
      '    while (j >= 0 && arr[j] > key) {',
      '      arr[j + 1] = arr[j];',
      '      j--;',
      '    }',
      '    arr[j + 1] = key;',
      '  }',
      '}',
    ],
    java: [
      'void insertionSort(int[] arr) {',
      '  int n = arr.length;',
      '  for (int i = 1; i < n; i++) {',
      '    int key = arr[i];',
      '    int j = i - 1;',
      '    while (j >= 0 && arr[j] > key) {',
      '      arr[j + 1] = arr[j];',
      '      j--;',
      '    }',
      '    arr[j + 1] = key;',
      '  }',
      '}',
    ],
  },

  merge: {
    pseudo: [
      'procedure mergeSort(arr[], left, right)',
      '  if left >= right then return',
      '  mid = (left + right) / 2',
      '  mergeSort(arr, left, mid)',
      '  mergeSort(arr, mid+1, right)',
      '  merge(arr, left, mid, right)',
      'end procedure',
      '',
      'procedure merge(arr[], l, m, r)',
      '  copy left and right subarrays',
      '  i = 0, j = 0, k = l',
      '  while i < leftLen and j < rightLen',
      '    if left[i] <= right[j]',
      '      arr[k] = left[i]; i++',
      '    else',
      '      arr[k] = right[j]; j++',
      '    k++',
      '  copy remaining elements',
      'end procedure',
    ],
    javascript: [
      'function mergeSort(arr, l = 0, r = arr.length - 1) {',
      '  if (l >= r) return;',
      '  const m = Math.floor((l + r) / 2);',
      '  mergeSort(arr, l, m);',
      '  mergeSort(arr, m + 1, r);',
      '  merge(arr, l, m, r);',
      '}',
      '',
      'function merge(arr, l, m, r) {',
      '  const L = arr.slice(l, m+1), R = arr.slice(m+1, r+1);',
      '  let i = 0, j = 0, k = l;',
      '  while (i < L.length && j < R.length) {',
      '    if (L[i] <= R[j]) arr[k++] = L[i++];',
      '    else arr[k++] = R[j++];',
      '  }',
      '  while (i < L.length) arr[k++] = L[i++];',
      '  while (j < R.length) arr[k++] = R[j++];',
      '',
      '}',
    ],
    python: [
      'def merge_sort(arr, l=0, r=None):',
      '    if r is None: r = len(arr) - 1',
      '    if l >= r: return',
      '    m = (l + r) // 2',
      '    merge_sort(arr, l, m)',
      '    merge_sort(arr, m + 1, r)',
      '    merge(arr, l, m, r)',
      '',
      'def merge(arr, l, m, r):',
      '    L, R = arr[l:m+1], arr[m+1:r+1]',
      '    i = j = 0; k = l',
      '    while i < len(L) and j < len(R):',
      '        if L[i] <= R[j]: arr[k] = L[i]; i += 1',
      '        else: arr[k] = R[j]; j += 1',
      '        k += 1',
      '    while i < len(L): arr[k] = L[i]; i += 1; k += 1',
      '    while j < len(R): arr[k] = R[j]; j += 1; k += 1',
      '',
      '',
    ],
    cpp: [
      'void mergeSort(int arr[], int l, int r) {',
      '  if (l >= r) return;',
      '  int m = (l + r) / 2;',
      '  mergeSort(arr, l, m);',
      '  mergeSort(arr, m + 1, r);',
      '  merge(arr, l, m, r);',
      '}',
      '',
      'void merge(int arr[], int l, int m, int r) {',
      '  // copy left[l..m] and right[m+1..r]',
      '  int i = 0, j = 0, k = l;',
      '  while (i < leftLen && j < rightLen) {',
      '    if (left[i] <= right[j]) arr[k++] = left[i++];',
      '    else arr[k++] = right[j++];',
      '  }',
      '  while (i < leftLen) arr[k++] = left[i++];',
      '  while (j < rightLen) arr[k++] = right[j++];',
      '',
      '}',
    ],
    java: [
      'void mergeSort(int[] arr, int l, int r) {',
      '  if (l >= r) return;',
      '  int m = (l + r) / 2;',
      '  mergeSort(arr, l, m);',
      '  mergeSort(arr, m + 1, r);',
      '  merge(arr, l, m, r);',
      '}',
      '',
      'void merge(int[] arr, int l, int m, int r) {',
      '  // copy left[l..m] and right[m+1..r]',
      '  int i = 0, j = 0, k = l;',
      '  while (i < leftLen && j < rightLen) {',
      '    if (left[i] <= right[j]) arr[k++] = left[i++];',
      '    else arr[k++] = right[j++];',
      '  }',
      '  while (i < leftLen) arr[k++] = left[i++];',
      '  while (j < rightLen) arr[k++] = right[j++];',
      '',
      '}',
    ],
  },

  quick: {
    pseudo: [
      'procedure quickSort(arr[], low, high)',
      '  if low >= high then return',
      '  pi = partition(arr, low, high)',
      '  quickSort(arr, low, pi - 1)',
      '  quickSort(arr, pi + 1, high)',
      'end procedure',
      '',
      'procedure partition(arr[], low, high)',
      '  pivot = arr[high]',
      '  i = low - 1',
      '  for j = low to high - 1',
      '    if arr[j] <= pivot',
      '      i++',
      '      swap(arr[i], arr[j])',
      '    end if',
      '  end for',
      '  swap(arr[i+1], arr[high])',
      '  return i + 1',
      'end procedure',
    ],
    javascript: [
      'function quickSort(arr, low = 0, high = arr.length - 1) {',
      '  if (low >= high) return;',
      '  const pi = partition(arr, low, high);',
      '  quickSort(arr, low, pi - 1);',
      '  quickSort(arr, pi + 1, high);',
      '}',
      '',
      'function partition(arr, low, high) {',
      '  const pivot = arr[high];',
      '  let i = low - 1;',
      '  for (let j = low; j < high; j++) {',
      '    if (arr[j] <= pivot) {',
      '      i++;',
      '      [arr[i], arr[j]] = [arr[j], arr[i]];',
      '    }',
      '  }',
      '  [arr[i+1], arr[high]] = [arr[high], arr[i+1]];',
      '  return i + 1;',
      '}',
    ],
    python: [
      'def quick_sort(arr, low=0, high=None):',
      '    if high is None: high = len(arr) - 1',
      '    if low >= high: return',
      '    pi = partition(arr, low, high)',
      '    quick_sort(arr, low, pi - 1)',
      '    quick_sort(arr, pi + 1, high)',
      '',
      'def partition(arr, low, high):',
      '    pivot = arr[high]',
      '    i = low - 1',
      '    for j in range(low, high):',
      '        if arr[j] <= pivot:',
      '            i += 1',
      '            arr[i], arr[j] = arr[j], arr[i]',
      '    ',
      '    arr[i+1], arr[high] = arr[high], arr[i+1]',
      '    return i + 1',
      '',
      '',
    ],
    cpp: [
      'void quickSort(int arr[], int low, int high) {',
      '  if (low >= high) return;',
      '  int pi = partition(arr, low, high);',
      '  quickSort(arr, low, pi - 1);',
      '  quickSort(arr, pi + 1, high);',
      '}',
      '',
      'int partition(int arr[], int low, int high) {',
      '  int pivot = arr[high];',
      '  int i = low - 1;',
      '  for (int j = low; j < high; j++) {',
      '    if (arr[j] <= pivot) {',
      '      i++;',
      '      swap(arr[i], arr[j]);',
      '    }',
      '  }',
      '  swap(arr[i + 1], arr[high]);',
      '  return i + 1;',
      '}',
    ],
    java: [
      'void quickSort(int[] arr, int low, int high) {',
      '  if (low >= high) return;',
      '  int pi = partition(arr, low, high);',
      '  quickSort(arr, low, pi - 1);',
      '  quickSort(arr, pi + 1, high);',
      '}',
      '',
      'int partition(int[] arr, int low, int high) {',
      '  int pivot = arr[high];',
      '  int i = low - 1;',
      '  for (int j = low; j < high; j++) {',
      '    if (arr[j] <= pivot) {',
      '      i++;',
      '      int temp = arr[i]; arr[i] = arr[j]; arr[j] = temp;',
      '    }',
      '  }',
      '  int temp = arr[i+1]; arr[i+1] = arr[high]; arr[high] = temp;',
      '  return i + 1;',
      '}',
    ],
  },
};

export const algorithmInfo: Record<string, { name: string; timeComplexity: string; spaceComplexity: string; stable: boolean }> = {
  bubble:    { name: 'Bubble Sort',    timeComplexity: 'O(n²)',      spaceComplexity: 'O(1)', stable: true },
  selection: { name: 'Selection Sort', timeComplexity: 'O(n²)',      spaceComplexity: 'O(1)', stable: false },
  insertion: { name: 'Insertion Sort', timeComplexity: 'O(n²)',      spaceComplexity: 'O(1)', stable: true },
  merge:     { name: 'Merge Sort',     timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', stable: true },
  quick:     { name: 'Quick Sort',     timeComplexity: 'O(n log n)', spaceComplexity: 'O(log n)', stable: false },
};
