import type { AlgorithmCode } from './types';

export const algorithmCodes: Record<string, AlgorithmCode> = {
  bubble: {
    pseudo: [
      'procedure bubbleSort(arr[], n)',
      '  for i = 0 to n-2',
      '    for j = 0 to n-i-2',
      '      if arr[j] > arr[j+1]',
      '        swap(arr[j], arr[j+1])',
      '      end if',
      '    end for',
      '  end for',
      'end procedure',
    ],
    javascript: [
      'function bubbleSort(arr) {',
      '  const n = arr.length;',
      '  for (let i = 0; i < n - 1; i++) {',
      '    for (let j = 0; j < n - i - 1; j++) {',
      '      if (arr[j] > arr[j + 1]) {',
      '        [arr[j], arr[j+1]] = [arr[j+1], arr[j]];',
      '      }',
      '    }',
      '  }',
      '}',
    ],
    python: [
      'def bubble_sort(arr):',
      '    n = len(arr)',
      '    for i in range(n - 1):',
      '        for j in range(n - i - 1):',
      '            if arr[j] > arr[j + 1]:',
      '                arr[j], arr[j+1] = arr[j+1], arr[j]',
      '',
      '',
      '',
      '',
    ],
    cpp: [
      'void bubbleSort(int arr[], int n) {',
      '  ',
      '  for (int i = 0; i < n - 1; i++) {',
      '    for (int j = 0; j < n - i - 1; j++) {',
      '      if (arr[j] > arr[j + 1]) {',
      '        swap(arr[j], arr[j + 1]);',
      '      }',
      '    }',
      '  }',
      '}',
    ],
    java: [
      'void bubbleSort(int[] arr) {',
      '  int n = arr.length;',
      '  for (int i = 0; i < n - 1; i++) {',
      '    for (int j = 0; j < n - i - 1; j++) {',
      '      if (arr[j] > arr[j + 1]) {',
      '        int temp = arr[j];',
      '        arr[j] = arr[j + 1];',
      '        arr[j + 1] = temp;',
      '      }',
      '    }',
      '  }',
      '}',
    ],
  },

  selection: {
    pseudo: [
      'procedure selectionSort(arr[], n)',
      '  for i = 0 to n-2',
      '    minIndex = i',
      '    for j = i+1 to n-1',
      '      if arr[j] < arr[minIndex]',
      '        minIndex = j',
      '      end if',
      '    end for',
      '    swap(arr[i], arr[minIndex])',
      '  end for',
      'end procedure',
    ],
    javascript: [
      'function selectionSort(arr) {',
      '  const n = arr.length;',
      '  for (let i = 0; i < n - 1; i++) {',
      '    let minIdx = i;',
      '    for (let j = i + 1; j < n; j++) {',
      '      if (arr[j] < arr[minIdx]) {',
      '        minIdx = j;',
      '      }',
      '    }',
      '    [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];',
      '  }',
      '}',
    ],
    python: [
      'def selection_sort(arr):',
      '    n = len(arr)',
      '    for i in range(n - 1):',
      '        min_idx = i',
      '        for j in range(i + 1, n):',
      '            if arr[j] < arr[min_idx]:',
      '                min_idx = j',
      '        ',
      '        arr[i], arr[min_idx] = arr[min_idx], arr[i]',
      '',
      '',
      '',
    ],
    cpp: [
      'void selectionSort(int arr[], int n) {',
      '  ',
      '  for (int i = 0; i < n - 1; i++) {',
      '    int minIdx = i;',
      '    for (int j = i + 1; j < n; j++) {',
      '      if (arr[j] < arr[minIdx]) {',
      '        minIdx = j;',
      '      }',
      '    }',
      '    swap(arr[i], arr[minIdx]);',
      '  }',
      '}',
    ],
    java: [
      'void selectionSort(int[] arr) {',
      '  int n = arr.length;',
      '  for (int i = 0; i < n - 1; i++) {',
      '    int minIdx = i;',
      '    for (int j = i + 1; j < n; j++) {',
      '      if (arr[j] < arr[minIdx]) {',
      '        minIdx = j;',
      '      }',
      '    }',
      '    int temp = arr[i];',
      '    arr[i] = arr[minIdx];',
      '    arr[minIdx] = temp;',
      '  }',
      '}',
    ],
  },

  insertion: {
    pseudo: [
      'procedure insertionSort(arr[], n)',
      '  for i = 1 to n-1',
      '    key = arr[i]',
      '    j = i - 1',
      '    while j >= 0 and arr[j] > key',
      '      arr[j+1] = arr[j]',
      '      j = j - 1',
      '    end while',
      '    arr[j+1] = key',
      '  end for',
      'end procedure',
    ],
    javascript: [
      'function insertionSort(arr) {',
      '  const n = arr.length;',
      '  for (let i = 1; i < n; i++) {',
      '    let key = arr[i];',
      '    let j = i - 1;',
      '    while (j >= 0 && arr[j] > key) {',
      '      arr[j + 1] = arr[j];',
      '      j--;',
      '    }',
      '    arr[j + 1] = key;',
      '  }',
      '}',
    ],
    python: [
      'def insertion_sort(arr):',
      '    n = len(arr)',
      '    for i in range(1, n):',
      '        key = arr[i]',
      '        j = i - 1',
      '        while j >= 0 and arr[j] > key:',
      '            arr[j + 1] = arr[j]',
      '            j -= 1',
      '        arr[j + 1] = key',
      '',
      '',
      '',
    ],
    cpp: [
      'void insertionSort(int arr[], int n) {',
      '  ',
      '  for (int i = 1; i < n; i++) {',
      '    int key = arr[i];',
      '    int j = i - 1;',
      '    while (j >= 0 && arr[j] > key) {',
      '      arr[j + 1] = arr[j];',
      '      j--;',
      '    }',
      '    arr[j + 1] = key;',
      '  }',
      '}',
    ],
    java: [
      'void insertionSort(int[] arr) {',
      '  int n = arr.length;',
      '  for (int i = 1; i < n; i++) {',
      '    int key = arr[i];',
      '    int j = i - 1;',
      '    while (j >= 0 && arr[j] > key) {',
      '      arr[j + 1] = arr[j];',
      '      j--;',
      '    }',
      '    arr[j + 1] = key;',
      '  }',
      '}',
    ],
  },

  merge: {
    pseudo: [
      'procedure mergeSort(arr[], left, right)',
      '  if left >= right then return',
      '  mid = (left + right) / 2',
      '  mergeSort(arr, left, mid)',
      '  mergeSort(arr, mid+1, right)',
      '  merge(arr, left, mid, right)',
      'end procedure',
      '',
      'procedure merge(arr[], l, m, r)',
      '  copy left and right subarrays',
      '  i = 0, j = 0, k = l',
      '  while i < leftLen and j < rightLen',
      '    if left[i] <= right[j]',
      '      arr[k] = left[i]; i++',
      '    else',
      '      arr[k] = right[j]; j++',
      '    k++',
      '  copy remaining elements',
      'end procedure',
    ],
    javascript: [
      'function mergeSort(arr, l = 0, r = arr.length - 1) {',
      '  if (l >= r) return;',
      '  const m = Math.floor((l + r) / 2);',
      '  mergeSort(arr, l, m);',
      '  mergeSort(arr, m + 1, r);',
      '  merge(arr, l, m, r);',
      '}',
      '',
      'function merge(arr, l, m, r) {',
      '  const L = arr.slice(l, m+1), R = arr.slice(m+1, r+1);',
      '  let i = 0, j = 0, k = l;',
      '  while (i < L.length && j < R.length) {',
      '    if (L[i] <= R[j]) arr[k++] = L[i++];',
      '    else arr[k++] = R[j++];',
      '  }',
      '  while (i < L.length) arr[k++] = L[i++];',
      '  while (j < R.length) arr[k++] = R[j++];',
      '',
      '}',
    ],
    python: [
      'def merge_sort(arr, l=0, r=None):',
      '    if r is None: r = len(arr) - 1',
      '    if l >= r: return',
      '    m = (l + r) // 2',
      '    merge_sort(arr, l, m)',
      '    merge_sort(arr, m + 1, r)',
      '    merge(arr, l, m, r)',
      '',
      'def merge(arr, l, m, r):',
      '    L, R = arr[l:m+1], arr[m+1:r+1]',
      '    i = j = 0; k = l',
      '    while i < len(L) and j < len(R):',
      '        if L[i] <= R[j]: arr[k] = L[i]; i += 1',
      '        else: arr[k] = R[j]; j += 1',
      '        k += 1',
      '    while i < len(L): arr[k] = L[i]; i += 1; k += 1',
      '    while j < len(R): arr[k] = R[j]; j += 1; k += 1',
      '',
      '',
    ],
    cpp: [
      'void mergeSort(int arr[], int l, int r) {',
      '  if (l >= r) return;',
      '  int m = (l + r) / 2;',
      '  mergeSort(arr, l, m);',
      '  mergeSort(arr, m + 1, r);',
      '  merge(arr, l, m, r);',
      '}',
      '',
      'void merge(int arr[], int l, int m, int r) {',
      '  // copy left[l..m] and right[m+1..r]',
      '  int i = 0, j = 0, k = l;',
      '  while (i < leftLen && j < rightLen) {',
      '    if (left[i] <= right[j]) arr[k++] = left[i++];',
      '    else arr[k++] = right[j++];',
      '  }',
      '  while (i < leftLen) arr[k++] = left[i++];',
      '  while (j < rightLen) arr[k++] = right[j++];',
      '',
      '}',
    ],
    java: [
      'void mergeSort(int[] arr, int l, int r) {',
      '  if (l >= r) return;',
      '  int m = (l + r) / 2;',
      '  mergeSort(arr, l, m);',
      '  mergeSort(arr, m + 1, r);',
      '  merge(arr, l, m, r);',
      '}',
      '',
      'void merge(int[] arr, int l, int m, int r) {',
      '  // copy left[l..m] and right[m+1..r]',
      '  int i = 0, j = 0, k = l;',
      '  while (i < leftLen && j < rightLen) {',
      '    if (left[i] <= right[j]) arr[k++] = left[i++];',
      '    else arr[k++] = right[j++];',
      '  }',
      '  while (i < leftLen) arr[k++] = left[i++];',
      '  while (j < rightLen) arr[k++] = right[j++];',
      '',
      '}',
    ],
  },

  quick: {
    pseudo: [
      'procedure quickSort(arr[], low, high)',
      '  if low >= high then return',
      '  pi = partition(arr, low, high)',
      '  quickSort(arr, low, pi - 1)',
      '  quickSort(arr, pi + 1, high)',
      'end procedure',
      '',
      'procedure partition(arr[], low, high)',
      '  pivot = arr[high]',
      '  i = low - 1',
      '  for j = low to high - 1',
      '    if arr[j] <= pivot',
      '      i++',
      '      swap(arr[i], arr[j])',
      '    end if',
      '  end for',
      '  swap(arr[i+1], arr[high])',
      '  return i + 1',
      'end procedure',
    ],
    javascript: [
      'function quickSort(arr, low = 0, high = arr.length - 1) {',
      '  if (low >= high) return;',
      '  const pi = partition(arr, low, high);',
      '  quickSort(arr, low, pi - 1);',
      '  quickSort(arr, pi + 1, high);',
      '}',
      '',
      'function partition(arr, low, high) {',
      '  const pivot = arr[high];',
      '  let i = low - 1;',
      '  for (let j = low; j < high; j++) {',
      '    if (arr[j] <= pivot) {',
      '      i++;',
      '      [arr[i], arr[j]] = [arr[j], arr[i]];',
      '    }',
      '  }',
      '  [arr[i+1], arr[high]] = [arr[high], arr[i+1]];',
      '  return i + 1;',
      '}',
    ],
    python: [
      'def quick_sort(arr, low=0, high=None):',
      '    if high is None: high = len(arr) - 1',
      '    if low >= high: return',
      '    pi = partition(arr, low, high)',
      '    quick_sort(arr, low, pi - 1)',
      '    quick_sort(arr, pi + 1, high)',
      '',
      'def partition(arr, low, high):',
      '    pivot = arr[high]',
      '    i = low - 1',
      '    for j in range(low, high):',
      '        if arr[j] <= pivot:',
      '            i += 1',
      '            arr[i], arr[j] = arr[j], arr[i]',
      '    ',
      '    arr[i+1], arr[high] = arr[high], arr[i+1]',
      '    return i + 1',
      '',
      '',
    ],
    cpp: [
      'void quickSort(int arr[], int low, int high) {',
      '  if (low >= high) return;',
      '  int pi = partition(arr, low, high);',
      '  quickSort(arr, low, pi - 1);',
      '  quickSort(arr, pi + 1, high);',
      '}',
      '',
      'int partition(int arr[], int low, int high) {',
      '  int pivot = arr[high];',
      '  int i = low - 1;',
      '  for (int j = low; j < high; j++) {',
      '    if (arr[j] <= pivot) {',
      '      i++;',
      '      swap(arr[i], arr[j]);',
      '    }',
      '  }',
      '  swap(arr[i + 1], arr[high]);',
      '  return i + 1;',
      '}',
    ],
    java: [
      'void quickSort(int[] arr, int low, int high) {',
      '  if (low >= high) return;',
      '  int pi = partition(arr, low, high);',
      '  quickSort(arr, low, pi - 1);',
      '  quickSort(arr, pi + 1, high);',
      '}',
      '',
      'int partition(int[] arr, int low, int high) {',
      '  int pivot = arr[high];',
      '  int i = low - 1;',
      '  for (int j = low; j < high; j++) {',
      '    if (arr[j] <= pivot) {',
      '      i++;',
      '      int temp = arr[i]; arr[i] = arr[j]; arr[j] = temp;',
      '    }',
      '  }',
      '  int temp = arr[i+1]; arr[i+1] = arr[high]; arr[high] = temp;',
      '  return i + 1;',
      '}',
    ],
  },

  linearSearch: {
    pseudo: [
      'procedure linearSearch(arr[], target)',
      '  for i = 0 to n-1',
      '    if arr[i] == target',
      '      return i',
      '    end if',
      '  end for',
      '  return -1',
      'end procedure',
    ],
    javascript: [
      'function linearSearch(arr, target) {',
      '  for (let i = 0; i < arr.length; i++) {',
      '    if (arr[i] === target) {',
      '      return i;',
      '    }',
      '  }',
      '  return -1;',
      '}',
    ],
    python: [
      'def linear_search(arr, target):',
      '    for i in range(len(arr)):',
      '        if arr[i] == target:',
      '            return i',
      '    return -1',
      '',
      '',
      '',
    ],
    cpp: [
      'int linearSearch(int arr[], int n, int target) {',
      '  for (int i = 0; i < n; i++) {',
      '    if (arr[i] == target) {',
      '      return i;',
      '    }',
      '  }',
      '  return -1;',
      '}',
    ],
    java: [
      'int linearSearch(int[] arr, int target) {',
      '  for (int i = 0; i < arr.length; i++) {',
      '    if (arr[i] == target) {',
      '      return i;',
      '    }',
      '  }',
      '  return -1;',
      '}',
    ],
  },

  binarySearch: {
    pseudo: [
      'procedure binarySearch(arr[], target)',
      '  low = 0, high = n-1',
      '  while low <= high',
      '    mid = (low + high) / 2',
      '    if arr[mid] == target',
      '      return mid',
      '    else if arr[mid] < target',
      '      low = mid + 1',
      '    else',
      '      high = mid - 1',
      '  return -1',
      'end procedure',
    ],
    javascript: [
      'function binarySearch(arr, target) {',
      '  let low = 0, high = arr.length - 1;',
      '  while (low <= high) {',
      '    const mid = Math.floor((low + high) / 2);',
      '    if (arr[mid] === target) return mid;',
      '    else if (arr[mid] < target) low = mid + 1;',
      '    else high = mid - 1;',
      '  }',
      '  return -1;',
      '}',
    ],
    python: [
      'def binary_search(arr, target):',
      '    low, high = 0, len(arr) - 1',
      '    while low <= high:',
      '        mid = (low + high) // 2',
      '        if arr[mid] == target:',
      '            return mid',
      '        elif arr[mid] < target:',
      '            low = mid + 1',
      '        else:',
      '            high = mid - 1',
      '    return -1',
    ],
    cpp: [
      'int binarySearch(int arr[], int n, int target) {',
      '  int low = 0, high = n - 1;',
      '  while (low <= high) {',
      '    int mid = (low + high) / 2;',
      '    if (arr[mid] == target) return mid;',
      '    else if (arr[mid] < target) low = mid + 1;',
      '    else high = mid - 1;',
      '  }',
      '  return -1;',
      '}',
    ],
    java: [
      'int binarySearch(int[] arr, int target) {',
      '  int low = 0, high = arr.length - 1;',
      '  while (low <= high) {',
      '    int mid = (low + high) / 2;',
      '    if (arr[mid] == target) return mid;',
      '    else if (arr[mid] < target) low = mid + 1;',
      '    else high = mid - 1;',
      '  }',
      '  return -1;',
      '}',
    ],
  },

  bstInsert: {
    pseudo: [
      'procedure insert(root, value)',
      '  if root is null',
      '    return new Node(value)',
      '  if value < root.val',
      '    root.left = insert(root.left, value)',
      '  else',
      '    root.right = insert(root.right, value)',
      '  return root',
      'end procedure',
      '',
      'procedure inorder(root)',
      '  if root is null then return',
      '  inorder(root.left)',
      '  visit root',
      '  inorder(root.right)',
      'end procedure',
    ],
    javascript: [
      'function insert(root, value) {',
      '  if (!root) return { val: value, left: null, right: null };',
      '  if (value < root.val)',
      '    root.left = insert(root.left, value);',
      '  else',
      '    root.right = insert(root.right, value);',
      '  return root;',
      '}',
      '',
      'function inorder(root) {',
      '  if (!root) return;',
      '  inorder(root.left);',
      '  console.log(root.val);',
      '  inorder(root.right);',
      '}',
    ],
    python: [
      'def insert(root, value):',
      '    if not root:',
      '        return Node(value)',
      '    if value < root.val:',
      '        root.left = insert(root.left, value)',
      '    else:',
      '        root.right = insert(root.right, value)',
      '    return root',
      '',
      'def inorder(root):',
      '    if not root: return',
      '    inorder(root.left)',
      '    print(root.val)',
      '    inorder(root.right)',
    ],
    cpp: [
      'Node* insert(Node* root, int val) {',
      '  if (!root) return new Node(val);',
      '  if (val < root->val)',
      '    root->left = insert(root->left, val);',
      '  else',
      '    root->right = insert(root->right, val);',
      '  return root;',
      '}',
      '',
      'void inorder(Node* root) {',
      '  if (!root) return;',
      '  inorder(root->left);',
      '  cout << root->val;',
      '  inorder(root->right);',
      '}',
    ],
    java: [
      'Node insert(Node root, int val) {',
      '  if (root == null) return new Node(val);',
      '  if (val < root.val)',
      '    root.left = insert(root.left, val);',
      '  else',
      '    root.right = insert(root.right, val);',
      '  return root;',
      '}',
      '',
      'void inorder(Node root) {',
      '  if (root == null) return;',
      '  inorder(root.left);',
      '  System.out.println(root.val);',
      '  inorder(root.right);',
      '}',
    ],
  },

  bstSearch: {
    pseudo: [
      'procedure search(root, target)',
      '  if root is null then return false',
      '  if root.val == target then return true',
      '  if target < root.val',
      '    return search(root.left, target)',
      '  else',
      '    return search(root.right, target)',
      'end procedure',
    ],
    javascript: [
      'function search(root, target) {',
      '  if (!root) return false;',
      '  if (root.val === target) return true;',
      '  if (target < root.val)',
      '    return search(root.left, target);',
      '  return search(root.right, target);',
      '}',
    ],
    python: [
      'def search(root, target):',
      '    if not root: return False',
      '    if root.val == target: return True',
      '    if target < root.val:',
      '        return search(root.left, target)',
      '    return search(root.right, target)',
      '',
      '',
      '',
    ],
    cpp: [
      'bool search(Node* root, int target) {',
      '  if (!root) return false;',
      '  if (root->val == target) return true;',
      '  if (target < root->val)',
      '    return search(root->left, target);',
      '  return search(root->right, target);',
      '}',
    ],
    java: [
      'boolean search(Node root, int target) {',
      '  if (root == null) return false;',
      '  if (root.val == target) return true;',
      '  if (target < root.val)',
      '    return search(root.left, target);',
      '  return search(root.right, target);',
      '}',
    ],
  },

  bstPreorder: {
    pseudo: [
      'procedure preorder(root)',
      '  if root is null then return',
      '  visit root',
      '  preorder(root.left)',
      '  preorder(root.right)',
      'end procedure',
    ],
    javascript: [
      'function preorder(root) {',
      '  if (!root) return;',
      '  console.log(root.val);',
      '  preorder(root.left);',
      '  preorder(root.right);',
      '}',
    ],
    python: [
      'def preorder(root):',
      '    if not root: return',
      '    print(root.val)',
      '    preorder(root.left)',
      '    preorder(root.right)',
      '',
      '',
      '',
    ],
    cpp: [
      'void preorder(Node* root) {',
      '  if (!root) return;',
      '  cout << root->val;',
      '  preorder(root->left);',
      '  preorder(root->right);',
      '}',
    ],
    java: [
      'void preorder(Node root) {',
      '  if (root == null) return;',
      '  System.out.println(root.val);',
      '  preorder(root.left);',
      '  preorder(root.right);',
      '}',
    ],
  },

  bstPostorder: {
    pseudo: [
      'procedure postorder(root)',
      '  if root is null then return',
      '  postorder(root.left)',
      '  postorder(root.right)',
      '  visit root',
      'end procedure',
    ],
    javascript: [
      'function postorder(root) {',
      '  if (!root) return;',
      '  postorder(root.left);',
      '  postorder(root.right);',
      '  console.log(root.val);',
      '}',
    ],
    python: [
      'def postorder(root):',
      '    if not root: return',
      '    postorder(root.left)',
      '    postorder(root.right)',
      '    print(root.val)',
      '',
      '',
      '',
    ],
    cpp: [
      'void postorder(Node* root) {',
      '  if (!root) return;',
      '  postorder(root->left);',
      '  postorder(root->right);',
      '  cout << root->val;',
      '}',
    ],
    java: [
      'void postorder(Node root) {',
      '  if (root == null) return;',
      '  postorder(root.left);',
      '  postorder(root.right);',
      '  System.out.println(root.val);',
      '}',
    ],
  },

  llTraversal: {
    pseudo: [
      'procedure traverse(head)',
      '  curr = head',
      '  while curr is not null',
      '    visit curr',
      '    curr = curr.next',
      '  end while',
      'end procedure',
    ],
    javascript: [
      'function traverse(head) {',
      '  let curr = head;',
      '  while (curr !== null) {',
      '    console.log(curr.val);',
      '    curr = curr.next;',
      '  }',
      '}',
    ],
    python: [
      'def traverse(head):',
      '    curr = head',
      '    while curr:',
      '        print(curr.val)',
      '        curr = curr.next',
      '',
      '',
      '',
    ],
    cpp: [
      'void traverse(Node* head) {',
      '  Node* curr = head;',
      '  while (curr != nullptr) {',
      '    cout << curr->val;',
      '    curr = curr->next;',
      '  }',
      '}',
    ],
    java: [
      'void traverse(Node head) {',
      '  Node curr = head;',
      '  while (curr != null) {',
      '    System.out.println(curr.val);',
      '    curr = curr.next;',
      '  }',
      '}',
    ],
  },

  llInsertHead: {
    pseudo: [
      'procedure insertHead(head, val)',
      '  newNode = Node(val)',
      '  newNode.next = head',
      '  head = newNode',
      '  return head',
      'end procedure',
    ],
    javascript: [
      'function insertHead(head, val) {',
      '  const newNode = { val, next: head };',
      '  return newNode;',
      '}',
    ],
    python: [
      'def insert_head(head, val):',
      '    new_node = Node(val)',
      '    new_node.next = head',
      '    return new_node',
      '',
      '',
      '',
    ],
    cpp: [
      'Node* insertHead(Node* head, int val) {',
      '  Node* newNode = new Node(val);',
      '  newNode->next = head;',
      '  return newNode;',
      '}',
    ],
    java: [
      'Node insertHead(Node head, int val) {',
      '  Node newNode = new Node(val);',
      '  newNode.next = head;',
      '  return newNode;',
      '}',
    ],
  },

  llInsertTail: {
    pseudo: [
      'procedure insertTail(head, val)',
      '  newNode = Node(val)',
      '  if head is null then return newNode',
      '  curr = head',
      '  while curr.next is not null',
      '    curr = curr.next',
      '  curr.next = newNode',
      '  return head',
      'end procedure',
    ],
    javascript: [
      'function insertTail(head, val) {',
      '  const newNode = { val, next: null };',
      '  if (!head) return newNode;',
      '  let curr = head;',
      '  while (curr.next) curr = curr.next;',
      '  curr.next = newNode;',
      '  return head;',
      '}',
    ],
    python: [
      'def insert_tail(head, val):',
      '    new_node = Node(val)',
      '    if not head: return new_node',
      '    curr = head',
      '    while curr.next:',
      '        curr = curr.next',
      '    curr.next = new_node',
      '    return head',
    ],
    cpp: [
      'Node* insertTail(Node* head, int val) {',
      '  Node* newNode = new Node(val);',
      '  if (!head) return newNode;',
      '  Node* curr = head;',
      '  while (curr->next) curr = curr->next;',
      '  curr->next = newNode;',
      '  return head;',
      '}',
    ],
    java: [
      'Node insertTail(Node head, int val) {',
      '  Node newNode = new Node(val);',
      '  if (head == null) return newNode;',
      '  Node curr = head;',
      '  while (curr.next != null) curr = curr.next;',
      '  curr.next = newNode;',
      '  return head;',
      '}',
    ],
  },

  llDelete: {
    pseudo: [
      'procedure delete(head, val)',
      '  if head.val == val then return head.next',
      '  curr = head',
      '  while curr.next is not null',
      '    if curr.next.val == val',
      '      curr.next = curr.next.next',
      '      return head',
      '    curr = curr.next',
      '  return head',
      'end procedure',
    ],
    javascript: [
      'function delete(head, val) {',
      '  if (head.val === val) return head.next;',
      '  let curr = head;',
      '  while (curr.next) {',
      '    if (curr.next.val === val) {',
      '      curr.next = curr.next.next;',
      '      return head;',
      '    }',
      '    curr = curr.next;',
      '  }',
      '  return head;',
      '}',
    ],
    python: [
      'def delete(head, val):',
      '    if head.val == val: return head.next',
      '    curr = head',
      '    while curr.next:',
      '        if curr.next.val == val:',
      '            curr.next = curr.next.next',
      '            return head',
      '        curr = curr.next',
      '    return head',
    ],
    cpp: [
      'Node* delete(Node* head, int val) {',
      '  if (head->val == val) return head->next;',
      '  Node* curr = head;',
      '  while (curr->next) {',
      '    if (curr->next->val == val) {',
      '      curr->next = curr->next->next;',
      '      return head;',
      '    }',
      '    curr = curr->next;',
      '  }',
      '  return head;',
      '}',
    ],
    java: [
      'Node delete(Node head, int val) {',
      '  if (head.val == val) return head.next;',
      '  Node curr = head;',
      '  while (curr.next != null) {',
      '    if (curr.next.val == val) {',
      '      curr.next = curr.next.next;',
      '      return head;',
      '    }',
      '    curr = curr.next;',
      '  }',
      '  return head;',
      '}',
    ],
  },

  llReverse: {
    pseudo: [
      'procedure reverse(head)',
      '  prev = null, curr = head',
      '  while curr is not null',
      '    next = curr.next',
      '    curr.next = prev',
      '    prev = curr',
      '    curr = next',
      '  return prev',
      'end procedure',
    ],
    javascript: [
      'function reverse(head) {',
      '  let prev = null, curr = head;',
      '  while (curr) {',
      '    const next = curr.next;',
      '    curr.next = prev;',
      '    prev = curr;',
      '    curr = next;',
      '  }',
      '  return prev;',
      '}',
    ],
    python: [
      'def reverse(head):',
      '    prev, curr = None, head',
      '    while curr:',
      '        nxt = curr.next',
      '        curr.next = prev',
      '        prev = curr',
      '        curr = nxt',
      '    return prev',
      '',
    ],
    cpp: [
      'Node* reverse(Node* head) {',
      '  Node* prev = nullptr;',
      '  Node* curr = head;',
      '  while (curr) {',
      '    Node* next = curr->next;',
      '    curr->next = prev;',
      '    prev = curr;',
      '    curr = next;',
      '  }',
      '  return prev;',
      '}',
    ],
    java: [
      'Node reverse(Node head) {',
      '  Node prev = null, curr = head;',
      '  while (curr != null) {',
      '    Node next = curr.next;',
      '    curr.next = prev;',
      '    prev = curr;',
      '    curr = next;',
      '  }',
      '  return prev;',
      '}',
    ],
  },

  llFindMiddle: {
    pseudo: [
      'procedure findMiddle(head)',
      '  slow = head, fast = head',
      '  while fast is not null and fast.next is not null',
      '    slow = slow.next',
      '    fast = fast.next.next',
      '  return slow',
      'end procedure',
    ],
    javascript: [
      'function findMiddle(head) {',
      '  let slow = head, fast = head;',
      '  while (fast && fast.next) {',
      '    slow = slow.next;',
      '    fast = fast.next.next;',
      '  }',
      '  return slow;',
      '}',
    ],
    python: [
      'def find_middle(head):',
      '    slow = fast = head',
      '    while fast and fast.next:',
      '        slow = slow.next',
      '        fast = fast.next.next',
      '    return slow',
      '',
      '',
    ],
    cpp: [
      'Node* findMiddle(Node* head) {',
      '  Node* slow = head;',
      '  Node* fast = head;',
      '  while (fast && fast->next) {',
      '    slow = slow->next;',
      '    fast = fast->next->next;',
      '  }',
      '  return slow;',
      '}',
    ],
    java: [
      'Node findMiddle(Node head) {',
      '  Node slow = head, fast = head;',
      '  while (fast != null && fast.next != null) {',
      '    slow = slow.next;',
      '    fast = fast.next.next;',
      '  }',
      '  return slow;',
      '}',
    ],
  },
};

export const algorithmInfo: Record<string, { name: string; timeComplexity: string; spaceComplexity: string; stable: boolean; category: string }> = {
  bubble:    { name: 'Bubble Sort',    timeComplexity: 'O(n²)',      spaceComplexity: 'O(1)', stable: true, category: 'sorting' },
  selection: { name: 'Selection Sort', timeComplexity: 'O(n²)',      spaceComplexity: 'O(1)', stable: false, category: 'sorting' },
  insertion: { name: 'Insertion Sort', timeComplexity: 'O(n²)',      spaceComplexity: 'O(1)', stable: true, category: 'sorting' },
  merge:     { name: 'Merge Sort',     timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', stable: true, category: 'sorting' },
  quick:     { name: 'Quick Sort',     timeComplexity: 'O(n log n)', spaceComplexity: 'O(log n)', stable: false, category: 'sorting' },
  linearSearch: { name: 'Linear Search', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', stable: false, category: 'searching' },
  binarySearch: { name: 'Binary Search', timeComplexity: 'O(log n)', spaceComplexity: 'O(1)', stable: false, category: 'searching' },
  bstInsert:    { name: 'BST Insert + Inorder', timeComplexity: 'O(n log n)', spaceComplexity: 'O(n)', stable: false, category: 'tree' },
  bstSearch:    { name: 'BST Search',    timeComplexity: 'O(log n)', spaceComplexity: 'O(h)', stable: false, category: 'tree' },
  bstPreorder:  { name: 'BST Preorder',  timeComplexity: 'O(n)', spaceComplexity: 'O(h)', stable: false, category: 'tree' },
  bstPostorder: { name: 'BST Postorder', timeComplexity: 'O(n)', spaceComplexity: 'O(h)', stable: false, category: 'tree' },
  llTraversal:  { name: 'LL Traversal',  timeComplexity: 'O(n)', spaceComplexity: 'O(1)', stable: false, category: 'linkedlist' },
  llInsertHead: { name: 'LL Insert Head', timeComplexity: 'O(1)', spaceComplexity: 'O(1)', stable: false, category: 'linkedlist' },
  llInsertTail: { name: 'LL Insert Tail', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', stable: false, category: 'linkedlist' },
  llDelete:     { name: 'LL Delete',     timeComplexity: 'O(n)', spaceComplexity: 'O(1)', stable: false, category: 'linkedlist' },
  llReverse:    { name: 'LL Reverse',    timeComplexity: 'O(n)', spaceComplexity: 'O(1)', stable: false, category: 'linkedlist' },
  llFindMiddle: { name: 'LL Find Middle', timeComplexity: 'O(n)', spaceComplexity: 'O(1)', stable: false, category: 'linkedlist' },
};
